/* Copyright (C) Gary Smith Partnership - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Gary Smith Partnership <gary@garysmithpartnership.com>, June, 2020
 */
global class GSP_SC_TriggerContext
{
	global static boolean DisableAllTriggers						= false;
	global static boolean DisableAccountTriggers					= false;
	global static boolean DisableBudgetTriggers						= false;
	global static boolean DisableCaseTriggers						= false;
	global static boolean DisableClinicBudgetTriggers				= false;
	global static boolean DisableEventTriggers						= false;
	global static boolean DisableInvoiceLineTriggers				= false;
	global static boolean DisableLeadTriggers						= false;
	global static boolean DisableOpportunityTriggers				= false;
	global static boolean DisableOpportunityLineItemTriggers		= false;
	global static boolean DisableRevenueScheduleTriggers			= false;   
	global static boolean DisableRevenueTargetTriggers				= false;
	global static boolean DisableOpportunityClosedWonTriggers		= false;   
}